// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/33cn/chain33/types"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Sign 签名
type Sign struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sign) Reset()         { *m = Sign{} }
func (m *Sign) String() string { return proto.CompactTextString(m) }
func (*Sign) ProtoMessage()    {}
func (*Sign) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *Sign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sign.Unmarshal(m, b)
}
func (m *Sign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sign.Marshal(b, m, deterministic)
}
func (m *Sign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sign.Merge(m, src)
}
func (m *Sign) XXX_Size() int {
	return xxx_messageInfo_Sign.Size(m)
}
func (m *Sign) XXX_DiscardUnknown() {
	xxx_messageInfo_Sign.DiscardUnknown(m)
}

var xxx_messageInfo_Sign proto.InternalMessageInfo

func (m *Sign) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Sign) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Friend struct {
	MainAddress          string   `protobuf:"bytes,1,opt,name=mainAddress,proto3" json:"mainAddress,omitempty"`
	FriendAddress        string   `protobuf:"bytes,2,opt,name=friendAddress,proto3" json:"friendAddress,omitempty"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Groups               []string `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}
func (*Friend) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *Friend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friend.Unmarshal(m, b)
}
func (m *Friend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friend.Marshal(b, m, deterministic)
}
func (m *Friend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friend.Merge(m, src)
}
func (m *Friend) XXX_Size() int {
	return xxx_messageInfo_Friend.Size(m)
}
func (m *Friend) XXX_DiscardUnknown() {
	xxx_messageInfo_Friend.DiscardUnknown(m)
}

var xxx_messageInfo_Friend proto.InternalMessageInfo

func (m *Friend) GetMainAddress() string {
	if m != nil {
		return m.MainAddress
	}
	return ""
}

func (m *Friend) GetFriendAddress() string {
	if m != nil {
		return m.FriendAddress
	}
	return ""
}

func (m *Friend) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Friend) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Black struct {
	MainAddress          string   `protobuf:"bytes,1,opt,name=mainAddress,proto3" json:"mainAddress,omitempty"`
	TargetAddress        string   `protobuf:"bytes,2,opt,name=targetAddress,proto3" json:"targetAddress,omitempty"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Black) Reset()         { *m = Black{} }
func (m *Black) String() string { return proto.CompactTextString(m) }
func (*Black) ProtoMessage()    {}
func (*Black) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *Black) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Black.Unmarshal(m, b)
}
func (m *Black) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Black.Marshal(b, m, deterministic)
}
func (m *Black) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Black.Merge(m, src)
}
func (m *Black) XXX_Size() int {
	return xxx_messageInfo_Black.Size(m)
}
func (m *Black) XXX_DiscardUnknown() {
	xxx_messageInfo_Black.DiscardUnknown(m)
}

var xxx_messageInfo_Black proto.InternalMessageInfo

func (m *Black) GetMainAddress() string {
	if m != nil {
		return m.MainAddress
	}
	return ""
}

func (m *Black) GetTargetAddress() string {
	if m != nil {
		return m.TargetAddress
	}
	return ""
}

func (m *Black) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type ChatAction struct {
	// Types that are valid to be assigned to Value:
	//	*ChatAction_Update
	//	*ChatAction_Black
	//	*ChatAction_UpdateUser
	//	*ChatAction_UpdateServerGroup
	Value                isChatAction_Value `protobuf_oneof:"value"`
	Ty                   int32              `protobuf:"varint,10,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChatAction) Reset()         { *m = ChatAction{} }
func (m *ChatAction) String() string { return proto.CompactTextString(m) }
func (*ChatAction) ProtoMessage()    {}
func (*ChatAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *ChatAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatAction.Unmarshal(m, b)
}
func (m *ChatAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatAction.Marshal(b, m, deterministic)
}
func (m *ChatAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatAction.Merge(m, src)
}
func (m *ChatAction) XXX_Size() int {
	return xxx_messageInfo_ChatAction.Size(m)
}
func (m *ChatAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatAction.DiscardUnknown(m)
}

var xxx_messageInfo_ChatAction proto.InternalMessageInfo

type isChatAction_Value interface {
	isChatAction_Value()
}

type ChatAction_Update struct {
	Update *UpdateFriends `protobuf:"bytes,1,opt,name=update,proto3,oneof"`
}

type ChatAction_Black struct {
	Black *UpdateBlackList `protobuf:"bytes,2,opt,name=black,proto3,oneof"`
}

type ChatAction_UpdateUser struct {
	UpdateUser *UpdateFields `protobuf:"bytes,3,opt,name=updateUser,proto3,oneof"`
}

type ChatAction_UpdateServerGroup struct {
	UpdateServerGroup *UpdateServerGroups `protobuf:"bytes,4,opt,name=updateServerGroup,proto3,oneof"`
}

func (*ChatAction_Update) isChatAction_Value() {}

func (*ChatAction_Black) isChatAction_Value() {}

func (*ChatAction_UpdateUser) isChatAction_Value() {}

func (*ChatAction_UpdateServerGroup) isChatAction_Value() {}

func (m *ChatAction) GetValue() isChatAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ChatAction) GetUpdate() *UpdateFriends {
	if x, ok := m.GetValue().(*ChatAction_Update); ok {
		return x.Update
	}
	return nil
}

func (m *ChatAction) GetBlack() *UpdateBlackList {
	if x, ok := m.GetValue().(*ChatAction_Black); ok {
		return x.Black
	}
	return nil
}

func (m *ChatAction) GetUpdateUser() *UpdateFields {
	if x, ok := m.GetValue().(*ChatAction_UpdateUser); ok {
		return x.UpdateUser
	}
	return nil
}

func (m *ChatAction) GetUpdateServerGroup() *UpdateServerGroups {
	if x, ok := m.GetValue().(*ChatAction_UpdateServerGroup); ok {
		return x.UpdateServerGroup
	}
	return nil
}

func (m *ChatAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ChatAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ChatAction_Update)(nil),
		(*ChatAction_Black)(nil),
		(*ChatAction_UpdateUser)(nil),
		(*ChatAction_UpdateServerGroup)(nil),
	}
}

//查询好友列表
type ReqGetFriends struct {
	MainAddress          string   `protobuf:"bytes,1,opt,name=mainAddress,proto3" json:"mainAddress,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Index                string   `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Sign                 *Sign    `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetFriends) Reset()         { *m = ReqGetFriends{} }
func (m *ReqGetFriends) String() string { return proto.CompactTextString(m) }
func (*ReqGetFriends) ProtoMessage()    {}
func (*ReqGetFriends) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *ReqGetFriends) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetFriends.Unmarshal(m, b)
}
func (m *ReqGetFriends) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetFriends.Marshal(b, m, deterministic)
}
func (m *ReqGetFriends) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetFriends.Merge(m, src)
}
func (m *ReqGetFriends) XXX_Size() int {
	return xxx_messageInfo_ReqGetFriends.Size(m)
}
func (m *ReqGetFriends) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetFriends.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetFriends proto.InternalMessageInfo

func (m *ReqGetFriends) GetMainAddress() string {
	if m != nil {
		return m.MainAddress
	}
	return ""
}

func (m *ReqGetFriends) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReqGetFriends) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ReqGetFriends) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ReqGetFriends) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ReplyGetFriends struct {
	Friends              []*Friend `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReplyGetFriends) Reset()         { *m = ReplyGetFriends{} }
func (m *ReplyGetFriends) String() string { return proto.CompactTextString(m) }
func (*ReplyGetFriends) ProtoMessage()    {}
func (*ReplyGetFriends) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *ReplyGetFriends) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyGetFriends.Unmarshal(m, b)
}
func (m *ReplyGetFriends) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyGetFriends.Marshal(b, m, deterministic)
}
func (m *ReplyGetFriends) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyGetFriends.Merge(m, src)
}
func (m *ReplyGetFriends) XXX_Size() int {
	return xxx_messageInfo_ReplyGetFriends.Size(m)
}
func (m *ReplyGetFriends) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyGetFriends.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyGetFriends proto.InternalMessageInfo

func (m *ReplyGetFriends) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

//更新好友列表
type ReqUpdateFriend struct {
	FriendAddress        string   `protobuf:"bytes,1,opt,name=friendAddress,proto3" json:"friendAddress,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Groups               []string `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdateFriend) Reset()         { *m = ReqUpdateFriend{} }
func (m *ReqUpdateFriend) String() string { return proto.CompactTextString(m) }
func (*ReqUpdateFriend) ProtoMessage()    {}
func (*ReqUpdateFriend) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{6}
}

func (m *ReqUpdateFriend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdateFriend.Unmarshal(m, b)
}
func (m *ReqUpdateFriend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdateFriend.Marshal(b, m, deterministic)
}
func (m *ReqUpdateFriend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdateFriend.Merge(m, src)
}
func (m *ReqUpdateFriend) XXX_Size() int {
	return xxx_messageInfo_ReqUpdateFriend.Size(m)
}
func (m *ReqUpdateFriend) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdateFriend.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdateFriend proto.InternalMessageInfo

func (m *ReqUpdateFriend) GetFriendAddress() string {
	if m != nil {
		return m.FriendAddress
	}
	return ""
}

func (m *ReqUpdateFriend) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqUpdateFriend) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

type UpdateFriends struct {
	Friends              []*ReqUpdateFriend `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateFriends) Reset()         { *m = UpdateFriends{} }
func (m *UpdateFriends) String() string { return proto.CompactTextString(m) }
func (*UpdateFriends) ProtoMessage()    {}
func (*UpdateFriends) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{7}
}

func (m *UpdateFriends) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFriends.Unmarshal(m, b)
}
func (m *UpdateFriends) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFriends.Marshal(b, m, deterministic)
}
func (m *UpdateFriends) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFriends.Merge(m, src)
}
func (m *UpdateFriends) XXX_Size() int {
	return xxx_messageInfo_UpdateFriends.Size(m)
}
func (m *UpdateFriends) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFriends.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFriends proto.InternalMessageInfo

func (m *UpdateFriends) GetFriends() []*ReqUpdateFriend {
	if m != nil {
		return m.Friends
	}
	return nil
}

//查询黑名单列表
type ReqGetBlackList struct {
	MainAddress          string   `protobuf:"bytes,1,opt,name=mainAddress,proto3" json:"mainAddress,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Index                string   `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Sign                 *Sign    `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetBlackList) Reset()         { *m = ReqGetBlackList{} }
func (m *ReqGetBlackList) String() string { return proto.CompactTextString(m) }
func (*ReqGetBlackList) ProtoMessage()    {}
func (*ReqGetBlackList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{8}
}

func (m *ReqGetBlackList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetBlackList.Unmarshal(m, b)
}
func (m *ReqGetBlackList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetBlackList.Marshal(b, m, deterministic)
}
func (m *ReqGetBlackList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetBlackList.Merge(m, src)
}
func (m *ReqGetBlackList) XXX_Size() int {
	return xxx_messageInfo_ReqGetBlackList.Size(m)
}
func (m *ReqGetBlackList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetBlackList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetBlackList proto.InternalMessageInfo

func (m *ReqGetBlackList) GetMainAddress() string {
	if m != nil {
		return m.MainAddress
	}
	return ""
}

func (m *ReqGetBlackList) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReqGetBlackList) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ReqGetBlackList) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ReqGetBlackList) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ReplyGetBlackList struct {
	List                 []*Black `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyGetBlackList) Reset()         { *m = ReplyGetBlackList{} }
func (m *ReplyGetBlackList) String() string { return proto.CompactTextString(m) }
func (*ReplyGetBlackList) ProtoMessage()    {}
func (*ReplyGetBlackList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{9}
}

func (m *ReplyGetBlackList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyGetBlackList.Unmarshal(m, b)
}
func (m *ReplyGetBlackList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyGetBlackList.Marshal(b, m, deterministic)
}
func (m *ReplyGetBlackList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyGetBlackList.Merge(m, src)
}
func (m *ReplyGetBlackList) XXX_Size() int {
	return xxx_messageInfo_ReplyGetBlackList.Size(m)
}
func (m *ReplyGetBlackList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyGetBlackList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyGetBlackList proto.InternalMessageInfo

func (m *ReplyGetBlackList) GetList() []*Black {
	if m != nil {
		return m.List
	}
	return nil
}

//更新黑名单请求
type ReqUpdateBlackList struct {
	TargetAddress        string   `protobuf:"bytes,1,opt,name=targetAddress,proto3" json:"targetAddress,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdateBlackList) Reset()         { *m = ReqUpdateBlackList{} }
func (m *ReqUpdateBlackList) String() string { return proto.CompactTextString(m) }
func (*ReqUpdateBlackList) ProtoMessage()    {}
func (*ReqUpdateBlackList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{10}
}

func (m *ReqUpdateBlackList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdateBlackList.Unmarshal(m, b)
}
func (m *ReqUpdateBlackList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdateBlackList.Marshal(b, m, deterministic)
}
func (m *ReqUpdateBlackList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdateBlackList.Merge(m, src)
}
func (m *ReqUpdateBlackList) XXX_Size() int {
	return xxx_messageInfo_ReqUpdateBlackList.Size(m)
}
func (m *ReqUpdateBlackList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdateBlackList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdateBlackList proto.InternalMessageInfo

func (m *ReqUpdateBlackList) GetTargetAddress() string {
	if m != nil {
		return m.TargetAddress
	}
	return ""
}

func (m *ReqUpdateBlackList) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type UpdateBlackList struct {
	List                 []*ReqUpdateBlackList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateBlackList) Reset()         { *m = UpdateBlackList{} }
func (m *UpdateBlackList) String() string { return proto.CompactTextString(m) }
func (*UpdateBlackList) ProtoMessage()    {}
func (*UpdateBlackList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{11}
}

func (m *UpdateBlackList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBlackList.Unmarshal(m, b)
}
func (m *UpdateBlackList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBlackList.Marshal(b, m, deterministic)
}
func (m *UpdateBlackList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBlackList.Merge(m, src)
}
func (m *UpdateBlackList) XXX_Size() int {
	return xxx_messageInfo_UpdateBlackList.Size(m)
}
func (m *UpdateBlackList) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBlackList.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBlackList proto.InternalMessageInfo

func (m *UpdateBlackList) GetList() []*ReqUpdateBlackList {
	if m != nil {
		return m.List
	}
	return nil
}

//------------------------user info----------------//
type Field struct {
	MainAddress          string   `protobuf:"bytes,1,opt,name=mainAddress,proto3" json:"mainAddress,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Level                string   `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{12}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetMainAddress() string {
	if m != nil {
		return m.MainAddress
	}
	return ""
}

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Field) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

//查询用户信息
type ReqGetUser struct {
	MainAddress          string   `protobuf:"bytes,1,opt,name=mainAddress,proto3" json:"mainAddress,omitempty"`
	TargetAddress        string   `protobuf:"bytes,2,opt,name=targetAddress,proto3" json:"targetAddress,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Index                string   `protobuf:"bytes,4,opt,name=index,proto3" json:"index,omitempty"`
	Time                 int64    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Sign                 *Sign    `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetUser) Reset()         { *m = ReqGetUser{} }
func (m *ReqGetUser) String() string { return proto.CompactTextString(m) }
func (*ReqGetUser) ProtoMessage()    {}
func (*ReqGetUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{13}
}

func (m *ReqGetUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetUser.Unmarshal(m, b)
}
func (m *ReqGetUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetUser.Marshal(b, m, deterministic)
}
func (m *ReqGetUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetUser.Merge(m, src)
}
func (m *ReqGetUser) XXX_Size() int {
	return xxx_messageInfo_ReqGetUser.Size(m)
}
func (m *ReqGetUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetUser.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetUser proto.InternalMessageInfo

func (m *ReqGetUser) GetMainAddress() string {
	if m != nil {
		return m.MainAddress
	}
	return ""
}

func (m *ReqGetUser) GetTargetAddress() string {
	if m != nil {
		return m.TargetAddress
	}
	return ""
}

func (m *ReqGetUser) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReqGetUser) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ReqGetUser) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ReqGetUser) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ReplyGetField struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Level                string   `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyGetField) Reset()         { *m = ReplyGetField{} }
func (m *ReplyGetField) String() string { return proto.CompactTextString(m) }
func (*ReplyGetField) ProtoMessage()    {}
func (*ReplyGetField) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{14}
}

func (m *ReplyGetField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyGetField.Unmarshal(m, b)
}
func (m *ReplyGetField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyGetField.Marshal(b, m, deterministic)
}
func (m *ReplyGetField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyGetField.Merge(m, src)
}
func (m *ReplyGetField) XXX_Size() int {
	return xxx_messageInfo_ReplyGetField.Size(m)
}
func (m *ReplyGetField) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyGetField.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyGetField proto.InternalMessageInfo

func (m *ReplyGetField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReplyGetField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ReplyGetField) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

type ReplyGetUser struct {
	ChatServers          []*ReplyServerInfo `protobuf:"bytes,1,rep,name=chatServers,proto3" json:"chatServers,omitempty"`
	Fields               []*ReplyGetField   `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Groups               []string           `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReplyGetUser) Reset()         { *m = ReplyGetUser{} }
func (m *ReplyGetUser) String() string { return proto.CompactTextString(m) }
func (*ReplyGetUser) ProtoMessage()    {}
func (*ReplyGetUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{15}
}

func (m *ReplyGetUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyGetUser.Unmarshal(m, b)
}
func (m *ReplyGetUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyGetUser.Marshal(b, m, deterministic)
}
func (m *ReplyGetUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyGetUser.Merge(m, src)
}
func (m *ReplyGetUser) XXX_Size() int {
	return xxx_messageInfo_ReplyGetUser.Size(m)
}
func (m *ReplyGetUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyGetUser.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyGetUser proto.InternalMessageInfo

func (m *ReplyGetUser) GetChatServers() []*ReplyServerInfo {
	if m != nil {
		return m.ChatServers
	}
	return nil
}

func (m *ReplyGetUser) GetFields() []*ReplyGetField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ReplyGetUser) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

//更新好友列表
type ReqUpdateField struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Level                string   `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdateField) Reset()         { *m = ReqUpdateField{} }
func (m *ReqUpdateField) String() string { return proto.CompactTextString(m) }
func (*ReqUpdateField) ProtoMessage()    {}
func (*ReqUpdateField) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{16}
}

func (m *ReqUpdateField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdateField.Unmarshal(m, b)
}
func (m *ReqUpdateField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdateField.Marshal(b, m, deterministic)
}
func (m *ReqUpdateField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdateField.Merge(m, src)
}
func (m *ReqUpdateField) XXX_Size() int {
	return xxx_messageInfo_ReqUpdateField.Size(m)
}
func (m *ReqUpdateField) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdateField.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdateField proto.InternalMessageInfo

func (m *ReqUpdateField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqUpdateField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ReqUpdateField) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqUpdateField) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

type UpdateFields struct {
	Fields               []*ReqUpdateField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateFields) Reset()         { *m = UpdateFields{} }
func (m *UpdateFields) String() string { return proto.CompactTextString(m) }
func (*UpdateFields) ProtoMessage()    {}
func (*UpdateFields) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{17}
}

func (m *UpdateFields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFields.Unmarshal(m, b)
}
func (m *UpdateFields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFields.Marshal(b, m, deterministic)
}
func (m *UpdateFields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFields.Merge(m, src)
}
func (m *UpdateFields) XXX_Size() int {
	return xxx_messageInfo_UpdateFields.Size(m)
}
func (m *UpdateFields) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFields.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFields proto.InternalMessageInfo

func (m *UpdateFields) GetFields() []*ReqUpdateField {
	if m != nil {
		return m.Fields
	}
	return nil
}

//--------------------------server groups-------------------------//
type ServerGroup struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	MainAddress          string   `protobuf:"bytes,4,opt,name=mainAddress,proto3" json:"mainAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerGroup) Reset()         { *m = ServerGroup{} }
func (m *ServerGroup) String() string { return proto.CompactTextString(m) }
func (*ServerGroup) ProtoMessage()    {}
func (*ServerGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{18}
}

func (m *ServerGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerGroup.Unmarshal(m, b)
}
func (m *ServerGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerGroup.Marshal(b, m, deterministic)
}
func (m *ServerGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerGroup.Merge(m, src)
}
func (m *ServerGroup) XXX_Size() int {
	return xxx_messageInfo_ServerGroup.Size(m)
}
func (m *ServerGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ServerGroup proto.InternalMessageInfo

func (m *ServerGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServerGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerGroup) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ServerGroup) GetMainAddress() string {
	if m != nil {
		return m.MainAddress
	}
	return ""
}

type UpdateServerGroups struct {
	Groups               []*ReqUpdateServerGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateServerGroups) Reset()         { *m = UpdateServerGroups{} }
func (m *UpdateServerGroups) String() string { return proto.CompactTextString(m) }
func (*UpdateServerGroups) ProtoMessage()    {}
func (*UpdateServerGroups) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{19}
}

func (m *UpdateServerGroups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServerGroups.Unmarshal(m, b)
}
func (m *UpdateServerGroups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServerGroups.Marshal(b, m, deterministic)
}
func (m *UpdateServerGroups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServerGroups.Merge(m, src)
}
func (m *UpdateServerGroups) XXX_Size() int {
	return xxx_messageInfo_UpdateServerGroups.Size(m)
}
func (m *UpdateServerGroups) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServerGroups.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServerGroups proto.InternalMessageInfo

func (m *UpdateServerGroups) GetGroups() []*ReqUpdateServerGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

//server groups request
//查询分组信息
type ReqGetServerGroup struct {
	MainAddress          string   `protobuf:"bytes,1,opt,name=mainAddress,proto3" json:"mainAddress,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Index                string   `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Sign                 *Sign    `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetServerGroup) Reset()         { *m = ReqGetServerGroup{} }
func (m *ReqGetServerGroup) String() string { return proto.CompactTextString(m) }
func (*ReqGetServerGroup) ProtoMessage()    {}
func (*ReqGetServerGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{20}
}

func (m *ReqGetServerGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetServerGroup.Unmarshal(m, b)
}
func (m *ReqGetServerGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetServerGroup.Marshal(b, m, deterministic)
}
func (m *ReqGetServerGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetServerGroup.Merge(m, src)
}
func (m *ReqGetServerGroup) XXX_Size() int {
	return xxx_messageInfo_ReqGetServerGroup.Size(m)
}
func (m *ReqGetServerGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetServerGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetServerGroup proto.InternalMessageInfo

func (m *ReqGetServerGroup) GetMainAddress() string {
	if m != nil {
		return m.MainAddress
	}
	return ""
}

func (m *ReqGetServerGroup) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReqGetServerGroup) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ReqGetServerGroup) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ReqGetServerGroup) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ReqUpdateServerGroup struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdateServerGroup) Reset()         { *m = ReqUpdateServerGroup{} }
func (m *ReqUpdateServerGroup) String() string { return proto.CompactTextString(m) }
func (*ReqUpdateServerGroup) ProtoMessage()    {}
func (*ReqUpdateServerGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{21}
}

func (m *ReqUpdateServerGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdateServerGroup.Unmarshal(m, b)
}
func (m *ReqUpdateServerGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdateServerGroup.Marshal(b, m, deterministic)
}
func (m *ReqUpdateServerGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdateServerGroup.Merge(m, src)
}
func (m *ReqUpdateServerGroup) XXX_Size() int {
	return xxx_messageInfo_ReqUpdateServerGroup.Size(m)
}
func (m *ReqUpdateServerGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdateServerGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdateServerGroup proto.InternalMessageInfo

func (m *ReqUpdateServerGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReqUpdateServerGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqUpdateServerGroup) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ReqUpdateServerGroup) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReplyServerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyServerInfo) Reset()         { *m = ReplyServerInfo{} }
func (m *ReplyServerInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyServerInfo) ProtoMessage()    {}
func (*ReplyServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{22}
}

func (m *ReplyServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyServerInfo.Unmarshal(m, b)
}
func (m *ReplyServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyServerInfo.Marshal(b, m, deterministic)
}
func (m *ReplyServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyServerInfo.Merge(m, src)
}
func (m *ReplyServerInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyServerInfo.Size(m)
}
func (m *ReplyServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyServerInfo proto.InternalMessageInfo

func (m *ReplyServerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReplyServerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReplyServerInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

//server groups reply
type ReplyGetServerGroup struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyGetServerGroup) Reset()         { *m = ReplyGetServerGroup{} }
func (m *ReplyGetServerGroup) String() string { return proto.CompactTextString(m) }
func (*ReplyGetServerGroup) ProtoMessage()    {}
func (*ReplyGetServerGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{23}
}

func (m *ReplyGetServerGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyGetServerGroup.Unmarshal(m, b)
}
func (m *ReplyGetServerGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyGetServerGroup.Marshal(b, m, deterministic)
}
func (m *ReplyGetServerGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyGetServerGroup.Merge(m, src)
}
func (m *ReplyGetServerGroup) XXX_Size() int {
	return xxx_messageInfo_ReplyGetServerGroup.Size(m)
}
func (m *ReplyGetServerGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyGetServerGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyGetServerGroup proto.InternalMessageInfo

func (m *ReplyGetServerGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReplyGetServerGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReplyGetServerGroup) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ReplyGetServerGroups struct {
	Groups               []*ReplyGetServerGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ReplyGetServerGroups) Reset()         { *m = ReplyGetServerGroups{} }
func (m *ReplyGetServerGroups) String() string { return proto.CompactTextString(m) }
func (*ReplyGetServerGroups) ProtoMessage()    {}
func (*ReplyGetServerGroups) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{24}
}

func (m *ReplyGetServerGroups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyGetServerGroups.Unmarshal(m, b)
}
func (m *ReplyGetServerGroups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyGetServerGroups.Marshal(b, m, deterministic)
}
func (m *ReplyGetServerGroups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyGetServerGroups.Merge(m, src)
}
func (m *ReplyGetServerGroups) XXX_Size() int {
	return xxx_messageInfo_ReplyGetServerGroups.Size(m)
}
func (m *ReplyGetServerGroups) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyGetServerGroups.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyGetServerGroups proto.InternalMessageInfo

func (m *ReplyGetServerGroups) GetGroups() []*ReplyGetServerGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

func init() {
	proto.RegisterType((*Sign)(nil), "types.Sign")
	proto.RegisterType((*Friend)(nil), "types.Friend")
	proto.RegisterType((*Black)(nil), "types.Black")
	proto.RegisterType((*ChatAction)(nil), "types.ChatAction")
	proto.RegisterType((*ReqGetFriends)(nil), "types.ReqGetFriends")
	proto.RegisterType((*ReplyGetFriends)(nil), "types.ReplyGetFriends")
	proto.RegisterType((*ReqUpdateFriend)(nil), "types.ReqUpdateFriend")
	proto.RegisterType((*UpdateFriends)(nil), "types.UpdateFriends")
	proto.RegisterType((*ReqGetBlackList)(nil), "types.ReqGetBlackList")
	proto.RegisterType((*ReplyGetBlackList)(nil), "types.ReplyGetBlackList")
	proto.RegisterType((*ReqUpdateBlackList)(nil), "types.ReqUpdateBlackList")
	proto.RegisterType((*UpdateBlackList)(nil), "types.UpdateBlackList")
	proto.RegisterType((*Field)(nil), "types.Field")
	proto.RegisterType((*ReqGetUser)(nil), "types.ReqGetUser")
	proto.RegisterType((*ReplyGetField)(nil), "types.ReplyGetField")
	proto.RegisterType((*ReplyGetUser)(nil), "types.ReplyGetUser")
	proto.RegisterType((*ReqUpdateField)(nil), "types.ReqUpdateField")
	proto.RegisterType((*UpdateFields)(nil), "types.UpdateFields")
	proto.RegisterType((*ServerGroup)(nil), "types.ServerGroup")
	proto.RegisterType((*UpdateServerGroups)(nil), "types.UpdateServerGroups")
	proto.RegisterType((*ReqGetServerGroup)(nil), "types.ReqGetServerGroup")
	proto.RegisterType((*ReqUpdateServerGroup)(nil), "types.ReqUpdateServerGroup")
	proto.RegisterType((*ReplyServerInfo)(nil), "types.ReplyServerInfo")
	proto.RegisterType((*ReplyGetServerGroup)(nil), "types.ReplyGetServerGroup")
	proto.RegisterType((*ReplyGetServerGroups)(nil), "types.ReplyGetServerGroups")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 937 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdb, 0x6e, 0xe3, 0x44,
	0x18, 0x8e, 0x63, 0x3b, 0x55, 0x7e, 0xf7, 0xa0, 0x4c, 0x4b, 0xe5, 0xcd, 0x22, 0x88, 0x46, 0x48,
	0xe4, 0x82, 0x8d, 0x20, 0x65, 0x25, 0x84, 0x40, 0xa2, 0x45, 0xa2, 0x5b, 0x40, 0x54, 0x9a, 0xdd,
	0x3e, 0x80, 0x1b, 0x4f, 0xb3, 0x16, 0xae, 0xe3, 0xb5, 0x27, 0xd5, 0xe6, 0x09, 0xe0, 0x8a, 0x0b,
	0x84, 0x78, 0x13, 0xde, 0x89, 0xc7, 0x40, 0x73, 0xb2, 0xc7, 0xf6, 0x44, 0x64, 0xb5, 0x7b, 0xb1,
	0x77, 0x9e, 0xff, 0x30, 0xf3, 0xfd, 0xdf, 0x7f, 0x98, 0x31, 0xc0, 0xe2, 0x65, 0xc4, 0x66, 0x79,
	0xb1, 0x62, 0x2b, 0xe4, 0xb3, 0x4d, 0x4e, 0xcb, 0xf1, 0x88, 0x15, 0x51, 0x56, 0x46, 0x0b, 0x96,
	0xac, 0x32, 0xa9, 0xc1, 0x17, 0xe0, 0x3d, 0x4f, 0x96, 0x19, 0xfa, 0x10, 0x86, 0xf9, 0xfa, 0x36,
	0x4d, 0x16, 0x3f, 0xd1, 0x4d, 0xe8, 0x4c, 0x9c, 0xe9, 0x90, 0xd4, 0x02, 0xae, 0x2d, 0x93, 0x65,
	0x16, 0xb1, 0x75, 0x41, 0xc3, 0xbe, 0xd4, 0x56, 0x02, 0xfc, 0xbb, 0x03, 0x83, 0x1f, 0x8a, 0x84,
	0x66, 0x31, 0x9a, 0x40, 0x70, 0x1f, 0x25, 0xd9, 0x79, 0x1c, 0x17, 0xb4, 0x2c, 0xd5, 0x46, 0xa6,
	0x08, 0x7d, 0x02, 0x07, 0x77, 0xc2, 0x56, 0xdb, 0xc8, 0xed, 0x9a, 0x42, 0xf4, 0x11, 0xc0, 0xa2,
	0xa0, 0x11, 0xa3, 0x2f, 0x92, 0x7b, 0x1a, 0xba, 0x13, 0x67, 0xea, 0x12, 0x43, 0x82, 0x4e, 0x61,
	0xb0, 0x2c, 0x56, 0xeb, 0xbc, 0x0c, 0xbd, 0x89, 0x3b, 0x1d, 0x12, 0xb5, 0xc2, 0x2b, 0xf0, 0x2f,
	0xd2, 0x68, 0xf1, 0xeb, 0x6e, 0x40, 0x58, 0x54, 0x2c, 0x29, 0x6b, 0x01, 0x69, 0x08, 0xff, 0x0f,
	0x08, 0xfe, 0xad, 0x0f, 0xf0, 0xfd, 0xcb, 0x88, 0x9d, 0x0b, 0x52, 0xd1, 0x0c, 0x06, 0xeb, 0x3c,
	0x8e, 0x18, 0x15, 0x27, 0x06, 0xf3, 0x93, 0x99, 0x60, 0x7e, 0x76, 0x23, 0x84, 0x92, 0xa4, 0xf2,
	0x59, 0x8f, 0x28, 0x2b, 0x34, 0x03, 0xff, 0x96, 0xe3, 0x15, 0x87, 0x07, 0xf3, 0xd3, 0x86, 0xb9,
	0x88, 0xe4, 0xe7, 0xa4, 0x64, 0xcf, 0x7a, 0x44, 0x9a, 0xa1, 0xa7, 0x00, 0xd2, 0xf3, 0xa6, 0xa4,
	0x85, 0x80, 0x13, 0xcc, 0x8f, 0x9b, 0x67, 0x24, 0x34, 0x15, 0x47, 0x18, 0x86, 0xe8, 0x0a, 0x46,
	0x72, 0xf5, 0x9c, 0x16, 0x0f, 0xb4, 0xb8, 0xe4, 0x64, 0x85, 0x9e, 0xf0, 0x7e, 0xd4, 0xf0, 0x36,
	0xf4, 0x7c, 0x8f, 0xae, 0x17, 0x3a, 0x84, 0x3e, 0xdb, 0x84, 0x30, 0x71, 0xa6, 0x3e, 0xe9, 0xb3,
	0xcd, 0xc5, 0x1e, 0xf8, 0x0f, 0x51, 0xba, 0xa6, 0xf8, 0x4f, 0x07, 0x0e, 0x08, 0x7d, 0x75, 0x49,
	0x99, 0x0a, 0x73, 0x87, 0x1c, 0x9c, 0x80, 0xbf, 0x58, 0xad, 0x33, 0x26, 0xc2, 0xf7, 0x89, 0x5c,
	0x70, 0x69, 0x92, 0xc5, 0xf4, 0xb5, 0x88, 0x6f, 0x48, 0xe4, 0x02, 0x21, 0xf0, 0x18, 0xcf, 0x81,
	0x27, 0x72, 0x20, 0xbe, 0xd1, 0xc7, 0xe0, 0xf1, 0x32, 0x0c, 0x7d, 0x11, 0x4a, 0xa0, 0x42, 0xe1,
	0x05, 0x4d, 0x84, 0x02, 0x7f, 0x0d, 0x47, 0x84, 0xe6, 0xe9, 0xc6, 0x40, 0xf5, 0x29, 0xec, 0xc9,
	0x5a, 0xe3, 0x88, 0xdc, 0x69, 0x30, 0x3f, 0x50, 0x6e, 0xd2, 0x80, 0x68, 0x2d, 0x5e, 0x70, 0xdf,
	0x57, 0x66, 0xe6, 0xba, 0xc5, 0xeb, 0xd8, 0x8a, 0x97, 0x23, 0xdd, 0xe4, 0x54, 0x05, 0x25, 0xbe,
	0x8d, 0x82, 0x75, 0x1b, 0x05, 0x7b, 0x0e, 0x07, 0x8d, 0xda, 0x40, 0x9f, 0xb7, 0xe1, 0xe9, 0x9a,
	0x68, 0x61, 0xa9, 0x71, 0xfe, 0xe5, 0x08, 0xa0, 0x97, 0x94, 0x55, 0x05, 0xf3, 0x3e, 0x50, 0xff,
	0x14, 0x46, 0x9a, 0x7a, 0x13, 0x97, 0x97, 0x26, 0x25, 0x53, 0xa1, 0xed, 0x2b, 0x2f, 0xa1, 0x27,
	0x42, 0x83, 0x7f, 0x01, 0x54, 0x45, 0x5a, 0xfb, 0x75, 0x9a, 0xd5, 0xb1, 0x35, 0xab, 0x85, 0x78,
	0xfc, 0x1d, 0x1c, 0xb5, 0x37, 0x7b, 0xd2, 0x00, 0xf1, 0xa8, 0xcd, 0x6f, 0x65, 0xa8, 0x10, 0x25,
	0xe0, 0x8b, 0xa6, 0xda, 0x81, 0x54, 0x04, 0x5e, 0x16, 0xdd, 0xeb, 0x11, 0x29, 0xbe, 0x39, 0xa5,
	0xa2, 0x41, 0x34, 0xa5, 0x62, 0xc1, 0xa5, 0x29, 0x7d, 0xa0, 0xa9, 0xe0, 0x74, 0x48, 0xe4, 0x02,
	0xff, 0xe3, 0x00, 0xc8, 0x54, 0x8a, 0xb6, 0x7d, 0x57, 0x43, 0xac, 0xca, 0xb5, 0x6b, 0xcd, 0xb5,
	0x67, 0xcb, 0xb5, 0x6f, 0xc9, 0xf5, 0x60, 0x5b, 0xae, 0xaf, 0x79, 0xeb, 0xab, 0x36, 0x13, 0x54,
	0x69, 0x22, 0x1c, 0x1b, 0x11, 0x7d, 0x2b, 0x11, 0xae, 0x49, 0xc4, 0x1f, 0x0e, 0xec, 0xeb, 0x1d,
	0x05, 0x15, 0x5f, 0x41, 0xc0, 0xef, 0x33, 0x39, 0x89, 0xba, 0xad, 0x91, 0xa7, 0x1b, 0xa9, 0xba,
	0xca, 0xee, 0x56, 0xc4, 0x34, 0x45, 0x9f, 0xc1, 0xe0, 0x4e, 0xcc, 0xc4, 0xb0, 0x2f, 0x9c, 0x4e,
	0x4c, 0x27, 0x0d, 0x98, 0x28, 0x9b, 0xad, 0x7d, 0x1a, 0xc3, 0x61, 0xdd, 0x80, 0x6f, 0x18, 0xa2,
	0x2e, 0x4b, 0xd7, 0x98, 0x07, 0xf6, 0xfc, 0x7f, 0x0b, 0xfb, 0xe6, 0x14, 0x47, 0x4f, 0x2a, 0xec,
	0x32, 0xe0, 0x0f, 0x3a, 0xb3, 0xc0, 0x04, 0x8f, 0x13, 0x08, 0x5a, 0xa3, 0x3a, 0x89, 0x15, 0xbe,
	0x7e, 0x12, 0xbf, 0x41, 0x75, 0xb6, 0x0a, 0xcf, 0xeb, 0x14, 0x1e, 0xbe, 0x02, 0xd4, 0xbd, 0x31,
	0xd0, 0x59, 0xc5, 0x9e, 0xc4, 0xfb, 0xb8, 0x8d, 0xd7, 0xb0, 0xae, 0xa8, 0xfd, 0xdb, 0xe1, 0x93,
	0x82, 0x17, 0xbd, 0x09, 0xfe, 0x3d, 0x98, 0x60, 0x31, 0x9c, 0xd8, 0x80, 0xbf, 0x05, 0xaf, 0xba,
	0x12, 0x3c, 0x63, 0x40, 0x5d, 0xab, 0x2b, 0xaa, 0xae, 0xdf, 0x9d, 0x0e, 0x08, 0x61, 0x2f, 0x52,
	0xdc, 0xc8, 0x23, 0xf4, 0x12, 0x5f, 0xc3, 0xb1, 0xae, 0xed, 0x77, 0x82, 0x1a, 0xff, 0xc8, 0x79,
	0xe8, 0x6c, 0x58, 0xa2, 0x79, 0x2b, 0xdb, 0xe3, 0x56, 0x67, 0x59, 0x92, 0x3d, 0xff, 0xd7, 0x05,
	0x8f, 0x77, 0x27, 0xfa, 0x02, 0x06, 0x92, 0x59, 0x64, 0x7d, 0x23, 0x8d, 0x8f, 0xb4, 0x34, 0xe3,
	0xb9, 0x78, 0xf1, 0x1a, 0xf7, 0xd0, 0x5c, 0x3f, 0xee, 0xb6, 0x3c, 0x93, 0x6c, 0x3e, 0x5f, 0x02,
	0xdc, 0xd4, 0xef, 0x20, 0xdb, 0x53, 0xc9, 0xe6, 0x75, 0x0e, 0xa3, 0x6e, 0xda, 0xb7, 0xbf, 0x94,
	0x6c, 0x5b, 0x7c, 0x03, 0x60, 0x3c, 0x3a, 0xea, 0xa1, 0x63, 0x3c, 0x90, 0xc6, 0xa7, 0xed, 0x51,
	0xa4, 0x6e, 0xf4, 0x1e, 0xba, 0x80, 0xfd, 0xc6, 0xbd, 0x79, 0xda, 0xf0, 0xaf, 0x23, 0x0e, 0x5b,
	0x3b, 0x54, 0x1a, 0xdc, 0x43, 0x67, 0xb0, 0xa7, 0xa7, 0xe7, 0xa8, 0xe1, 0xce, 0x45, 0xe3, 0xe3,
	0x96, 0x27, 0x17, 0xe2, 0x1e, 0xba, 0x82, 0xc3, 0x56, 0xdd, 0x84, 0x0d, 0x5f, 0x43, 0x33, 0x7e,
	0xbc, 0x3d, 0xdf, 0x25, 0xee, 0xdd, 0x0e, 0xc4, 0x1f, 0xc6, 0xd9, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x41, 0x9f, 0x72, 0x65, 0x89, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	Update(ctx context.Context, in *UpdateFriends, opts ...grpc.CallOption) (*types.UnsignTx, error)
	Black(ctx context.Context, in *UpdateBlackList, opts ...grpc.CallOption) (*types.UnsignTx, error)
	UpdateUser(ctx context.Context, in *UpdateFields, opts ...grpc.CallOption) (*types.UnsignTx, error)
	UpdateServerGroup(ctx context.Context, in *UpdateServerGroups, opts ...grpc.CallOption) (*types.UnsignTx, error)
	GetFriends(ctx context.Context, in *ReqGetFriends, opts ...grpc.CallOption) (*ReplyGetFriends, error)
	GetBlackList(ctx context.Context, in *ReqGetBlackList, opts ...grpc.CallOption) (*ReplyGetBlackList, error)
	GetUser(ctx context.Context, in *ReqGetUser, opts ...grpc.CallOption) (*ReplyGetUser, error)
	GetServerGroup(ctx context.Context, in *ReqGetServerGroup, opts ...grpc.CallOption) (*ReplyGetServerGroups, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Update(ctx context.Context, in *UpdateFriends, opts ...grpc.CallOption) (*types.UnsignTx, error) {
	out := new(types.UnsignTx)
	err := c.cc.Invoke(ctx, "/types.chat/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Black(ctx context.Context, in *UpdateBlackList, opts ...grpc.CallOption) (*types.UnsignTx, error) {
	out := new(types.UnsignTx)
	err := c.cc.Invoke(ctx, "/types.chat/Black", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) UpdateUser(ctx context.Context, in *UpdateFields, opts ...grpc.CallOption) (*types.UnsignTx, error) {
	out := new(types.UnsignTx)
	err := c.cc.Invoke(ctx, "/types.chat/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) UpdateServerGroup(ctx context.Context, in *UpdateServerGroups, opts ...grpc.CallOption) (*types.UnsignTx, error) {
	out := new(types.UnsignTx)
	err := c.cc.Invoke(ctx, "/types.chat/UpdateServerGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetFriends(ctx context.Context, in *ReqGetFriends, opts ...grpc.CallOption) (*ReplyGetFriends, error) {
	out := new(ReplyGetFriends)
	err := c.cc.Invoke(ctx, "/types.chat/GetFriends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetBlackList(ctx context.Context, in *ReqGetBlackList, opts ...grpc.CallOption) (*ReplyGetBlackList, error) {
	out := new(ReplyGetBlackList)
	err := c.cc.Invoke(ctx, "/types.chat/GetBlackList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetUser(ctx context.Context, in *ReqGetUser, opts ...grpc.CallOption) (*ReplyGetUser, error) {
	out := new(ReplyGetUser)
	err := c.cc.Invoke(ctx, "/types.chat/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetServerGroup(ctx context.Context, in *ReqGetServerGroup, opts ...grpc.CallOption) (*ReplyGetServerGroups, error) {
	out := new(ReplyGetServerGroups)
	err := c.cc.Invoke(ctx, "/types.chat/GetServerGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	Update(context.Context, *UpdateFriends) (*types.UnsignTx, error)
	Black(context.Context, *UpdateBlackList) (*types.UnsignTx, error)
	UpdateUser(context.Context, *UpdateFields) (*types.UnsignTx, error)
	UpdateServerGroup(context.Context, *UpdateServerGroups) (*types.UnsignTx, error)
	GetFriends(context.Context, *ReqGetFriends) (*ReplyGetFriends, error)
	GetBlackList(context.Context, *ReqGetBlackList) (*ReplyGetBlackList, error)
	GetUser(context.Context, *ReqGetUser) (*ReplyGetUser, error)
	GetServerGroup(context.Context, *ReqGetServerGroup) (*ReplyGetServerGroups, error)
}

// UnimplementedChatServer can be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (*UnimplementedChatServer) Update(ctx context.Context, req *UpdateFriends) (*types.UnsignTx, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedChatServer) Black(ctx context.Context, req *UpdateBlackList) (*types.UnsignTx, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Black not implemented")
}
func (*UnimplementedChatServer) UpdateUser(ctx context.Context, req *UpdateFields) (*types.UnsignTx, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedChatServer) UpdateServerGroup(ctx context.Context, req *UpdateServerGroups) (*types.UnsignTx, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServerGroup not implemented")
}
func (*UnimplementedChatServer) GetFriends(ctx context.Context, req *ReqGetFriends) (*ReplyGetFriends, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriends not implemented")
}
func (*UnimplementedChatServer) GetBlackList(ctx context.Context, req *ReqGetBlackList) (*ReplyGetBlackList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlackList not implemented")
}
func (*UnimplementedChatServer) GetUser(ctx context.Context, req *ReqGetUser) (*ReplyGetUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedChatServer) GetServerGroup(ctx context.Context, req *ReqGetServerGroup) (*ReplyGetServerGroups, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerGroup not implemented")
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriends)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.chat/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Update(ctx, req.(*UpdateFriends))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Black_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlackList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Black(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.chat/Black",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Black(ctx, req.(*UpdateBlackList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFields)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.chat/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).UpdateUser(ctx, req.(*UpdateFields))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_UpdateServerGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerGroups)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).UpdateServerGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.chat/UpdateServerGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).UpdateServerGroup(ctx, req.(*UpdateServerGroups))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetFriends)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.chat/GetFriends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetFriends(ctx, req.(*ReqGetFriends))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetBlackList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.chat/GetBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetBlackList(ctx, req.(*ReqGetBlackList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.chat/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetUser(ctx, req.(*ReqGetUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetServerGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetServerGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetServerGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.chat/GetServerGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetServerGroup(ctx, req.(*ReqGetServerGroup))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _Chat_Update_Handler,
		},
		{
			MethodName: "Black",
			Handler:    _Chat_Black_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Chat_UpdateUser_Handler,
		},
		{
			MethodName: "UpdateServerGroup",
			Handler:    _Chat_UpdateServerGroup_Handler,
		},
		{
			MethodName: "GetFriends",
			Handler:    _Chat_GetFriends_Handler,
		},
		{
			MethodName: "GetBlackList",
			Handler:    _Chat_GetBlackList_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Chat_GetUser_Handler,
		},
		{
			MethodName: "GetServerGroup",
			Handler:    _Chat_GetServerGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
